version: '3.7'

services:
    webapp-server:
      build:
        context: .
        dockerfile: Dockerfile
      image: schoolapp-server-img
      container_name: schoolapp-node-express
      volumes:
       - .:/usr/src/schoolapp
       - /usr/src/schoolapp/node_modules
      ports:
        - "3300:8080"
      depends_on:
        - mongo
      # env_file: .env
      environment:
        - MONGO_HOSTNAME=$MONGO_HOSTNAME
        - MONGO_PORT=$MONGO_PORT
        - MONGO_DB=$MONGO_DB
    mongo:
      image: mongo
      container_name: schoolapp-mongodb
      ports:
        - "27017:27017"